apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.loki.service.port }}
      targetPort: {{ .Values.loki.service.port }}
      protocol: TCP
      name: http
  selector:
    app: loki
